# Generated by Django 5.0.6 on 2024-05-27 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='todo', max_length=20),
        ),
    ]
