# Generated by Django 5.0.6 on 2024-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0002_task_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='due_date',
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(default='main', max_length=20),
        ),
    ]
