# Generated by Django 5.0.6 on 2024-06-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_task_category_color_task_status_alter_task_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
