# Generated by Django 5.0.6 on 2024-06-01 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0009_task_category_color_alter_task_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='category_color',
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='join.taskcategory'),
        ),
    ]
